In [18]:
import pickle
import numpy as np
from importnb import Notebook


'''
Objects, which are used here as an example, were created with the class "Backend". 
The subsequent division into 'Backend' and 'Backend_roc' for multiclass scenarios was
not yet available at this time, which is why 'Backend' is imported from the 
'SHAP_approach_synthetic_data' folder here, although this exemplary objects represent a real-world scenario.
'''
ShapDetectorClass = Notebook.load('./SHAP_approach_synthetic_data/Backend.ipynb')
ShapDetector = ShapDetectorClass.ShapDetector

### Compute metrics for object with reduced set of featues

In [27]:
# load object with reduced set of features
d_reduced = pickle.load( open( "./Results/Detector_objs/Test_Insects_abrupt_red/2020_11_05_02_00_58_758.pickle", "rb" ) ) # 2020_11_01_17_16_23_562.pickle originates from 
dist_list_reduced = d_reduced.distances
acc_list_reduced = d_reduced.score_list

window = 50

# compute bins
dist_list_reduced_c = []
for i,idx in enumerate(dist_list_reduced):
    if i%window != 0:
        dist_list_reduced_c.append(np.mean(dist_list_reduced[i-window:i]))
        
acc_list_reduced_c = []
for i,idx in enumerate(acc_list_reduced):
    if i%window != 0:
        acc_list_reduced_c.append(np.mean(acc_list_reduced[i-window:i]))

acc_list_reduced_c = acc_list_reduced_c[window-1:]
dist_list_reduced_c = dist_list_reduced_c[window-1:]

In [20]:
print('mean acc list', np.mean(acc_list_reduced))
print('std dist list', np.std(dist_list_reduced))
print('var dist list', np.var(dist_list_reduced))
print(np.corrcoef(dist_list_reduced,acc_list_reduced, 'valid'))

mean acc list 0.5634784687089193
std dist list 0.10753451243704895
var dist list 0.011563671365073835
[[ 1.         -0.01816091]
 [-0.01816091  1.        ]]


#### Compute metrics for data compressed in bins 

In [21]:
print('mean acc list c', np.mean(acc_list_reduced_c))
print('std dist list c', np.std(dist_list_reduced_c))
print('var dist list c', np.var(dist_list_reduced_c))
print()
print('correlation \n', np.corrcoef(dist_list_reduced_c,acc_list_reduced_c, 'valid'))

mean acc list c 0.5636592610677084
std dist list c 0.028201857115179398
var dist list c 0.0007953447447449949

correlation 
 [[ 1.         -0.20891617]
 [-0.20891617  1.        ]]


---
### Compute metrics for object with the full set of featues

In [26]:
# load object with the full set of features
d_all = pickle.load( open( "./Results/Detector_objs/check_correlation/Insects_abrupt_bal_no_retraining.pickle", "rb" ) )
dist_list_all = d_all.distances
acc_list_all = d_all.score_list

window = 50

# compute bins
dist_list_all_c = []
for i,idx in enumerate(dist_list_all):
    if i%window != 0:
        dist_list_all_c.append(np.mean(dist_list_all[i-window:i]))

acc_list_all_c = []
for i,idx in enumerate(acc_list_all):
    if i%window != 0:
        acc_list_all_c.append(np.mean(acc_list_all[i-window:i]))

acc_list_all_c = acc_list_all_c[window-1:]
dist_list_all_c = dist_list_all_c[window-1:]

In [23]:
print('mean acc list', np.mean(acc_list_all))
print('std dist list', np.std(dist_list_all))
print('var dist list', np.var(dist_list_all))
print(np.corrcoef(dist_list_all,acc_list_all, 'valid'))

mean acc list 0.568696968489822
std dist list 0.09262318101350084
var dist list 0.008579053661059741
[[1.         0.03941434]
 [0.03941434 1.        ]]


#### Compute metrics for data compressed in bins

In [24]:
print('mean acc list c', np.mean(acc_list_all_c))
print('std dist list c', np.std(dist_list_all_c))
print('var dist list c', np.var(dist_list_all_c))
print()
print('correlation \n', np.corrcoef(dist_list_all_c,acc_list_all_c, 'valid'))

mean acc list c 0.568916015625
std dist list c 0.02012450279447859
var dist list c 0.0004049956127249765

correlation 
 [[ 1.         -0.14423613]
 [-0.14423613  1.        ]]
